### ISSUE TITLE
CLI Skeleton

### ISSUE THREAD

**Issue by endorama** [elastic/elastic-agent-changelog-tool#3]
Create CLI skeleton and basic development tooling.

- [x] main and root CMD
- [x] basic `Makefile` with `build`, `test` targets
- [x] CI running `make test`
- [x] #19

**Comment by v1v** [comment]
I've just seen this, is there any plan to support this within the existing CI platform? This is sort of automated in https://beats-ci.elastic.co/job/robots/job/onboarding-ci-pipeline/ but it requires to grant write access to the GitHub `elasticmachine` in the repository.

**Comment by andresrc** [comment]
Thanks @v1v , I just granted write access to `elasticmachine`

**Comment by LucianPy** [comment]
Deleted Github Actions from the branch.

**Comment by v1v** [comment]
There is a missing configuration regarding the webhooks, unfortunately I'm not admin and I cannot fix this.


Manually through the UI -> https://github.com/elastic/elastic-agent-changelog-tool/settings/hooks

<img width="685" alt="image" src="https://user-images.githubusercontent.com/2871786/155169144-823b0527-4ea0-4306-9e4c-11241bbe69ec.png">

<img width="993" alt="image" src="https://user-images.githubusercontent.com/2871786/155169044-4e8a2a58-687b-4944-aad4-94c2a5ad496f.png">


Or 

```
curl -u "$(GITHUB_USER):$(GITHUB_TOKEN)" \
	  -v \
	  -H "Content-Type: application/json" -X POST \
	  -d '{"name": "web", "active": true, "events": ["push", "issue_comment", "pull_request"], "config": {"url": "https://beats-ci.elastic.co/github-webhook/", "content_type": "json"}}' \
	  https://api.github.com/repos/elastic/$(PROJECT)/hooks
```

**Comment by endorama** [comment]
I'm not an admin too, so waiting for @andresrc to come back from PTO. Thank you @v1v for stepping in!

**Comment by endorama** [comment]
Closing as all tasks have been completed
