### ISSUE TITLE
Fix changelog pr/issue empty field case

### ISSUE THREAD

**Issue by LucianPy** [elastic/elastic-agent-changelog-tool#70]
In case the tool is not able to automatically complete the pr/issue fields it will require manual user editing.

The changelog will default those fields to `[]` (empty slice of ints). 

We would want this to actually default to an empty field entirely so the user doesn't have to delete this every time.

**Comment by endorama** [comment]
I think this can be done with [`omitempty` field tag.](https://pkg.go.dev/gopkg.in/yaml.v2#Marshal)

**Comment by LucianPy** [comment]
The `omitempty` tag will actually remove the field entirely from the changelog in case it's empty.

I could add it to the repository, description and component as well to slim the changelog down if it's alright.

**Comment by LucianPy** [comment]
We've decided the added complexity needed for this is not worth it. Closing.
